# jekyll configuration
# --------------------
highlighter: rouge
markdown: kramdown

# site configuration
# ------------------
title: Multiple Subtasks for Jira

# url configuration
# -----------------
github_url: https://github.com/codescape/jira-multiple-subtasks
marketplace_url: https://marketplace.atlassian.com/apps/1229293/multiple-subtasks-for-jira
servicedesk_url: https://codescape.atlassian.net/servicedesk

# contact data
# ------------
contact_mail: support@codescape.atlassian.net
