# jekyll configuration
# --------------------
highlighter: rouge
markdown: kramdown

# site configuration
# ------------------
title: Multiple Subtasks for Jira

# url configuration
# -----------------
github_url: https://github.com/codescape/jira-multiple-subtasks
# TODO change marketplace URL when product is listed on marketplace
marketplace_url: https://marketplace.atlassian.com/vendors/1215070/codescape-stefan-glase
servicedesk_url: https://codescape.atlassian.net/servicedesk

# contact data
# ------------
contact_mail: support@codescape.atlassian.net
